In [1]:
!pip install prophet pandas

Requirement already satisfied: prophet in /usr/local/lib/python3.12/dist-packages (1.1.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (1.2.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.0.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from prophet) (3.10.0)
Requirement already satisfied: holidays<1,>=0.25 in /usr/local/lib/python3.12/dist-packages (from prophet) (0.82)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from prophet) (4.67.1)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from prophet) (6.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (3.2.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [37]:
import pandas as pd
import random as rd

STARTING_BALANCE = 2000.00
PAYCHECK_DAYS = (1, 15)
PAYCHECK_AMOUNT = 900.00
BILLS_DAY = 1
BILLS_AMOUNT = 850.00
WEEKDAYS_EXPENSE_LIMITS = (5.00, 40.00)
WEEKEND_EXPENSE_LIMITS = (20.00, 100.00)

date_range = pd.date_range(start='2023-01-01', periods=1000, freq='D')
df = pd.DataFrame(date_range, columns=['ds'])
df['y'] = 0.00

current_balance = STARTING_BALANCE
spending_probabilities = [0.5, 0.2, 0.4, 0.5, 0.75, 0.9, 0.6]
for date in date_range:
    if date.day in PAYCHECK_DAYS:
        current_balance += PAYCHECK_AMOUNT
    if date.day == BILLS_DAY:
        current_balance -= BILLS_AMOUNT

    day_of_week = date.weekday()
    if rd.random() < spending_probabilities[day_of_week]:
        if day_of_week < 4:
            current_balance -= rd.uniform(WEEKDAYS_EXPENSE_LIMITS[0], WEEKDAYS_EXPENSE_LIMITS[1])
        else:
            current_balance -= rd.uniform(WEEKEND_EXPENSE_LIMITS[0], WEEKEND_EXPENSE_LIMITS[1])

    df.loc[df['ds'] == date, 'y'] = round(current_balance, 2) # Round to two decimal places

display(df)

            ds        y
0   2023-01-01  2011.42
1   2023-01-02  2011.42
2   2023-01-03  2011.42
3   2023-01-04  2011.42
4   2023-01-05  1977.05
..         ...      ...
995 2025-09-22  8779.15
996 2025-09-23  8763.70
997 2025-09-24  8741.86
998 2025-09-25  8704.96
999 2025-09-26  8684.33

[1000 rows x 2 columns]

In [38]:
from prophet import Prophet

model = Prophet(daily_seasonality=False, weekly_seasonality=True, yearly_seasonality=False)
model.add_seasonality(name='monthly', period=30.5, fourier_order=5)
model.add_seasonality(name='paycheck', period=14, fourier_order=5)
model.fit(df)

future = model.make_future_dataframe(periods=30)
forecast = model.predict(future)

display(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(30))

DEBUG:cmdstanpy:input tempfile: /tmp/tmpgkd32vpo/bb30ze5v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpgkd32vpo/j2sjoyq3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74756', 'data', 'file=/tmp/tmpgkd32vpo/bb30ze5v.json', 'init=/tmp/tmpgkd32vpo/j2sjoyq3.json', 'output', 'file=/tmp/tmpgkd32vpo/prophet_model5zs0q8tz/prophet_model-20251018211414.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
21:14:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
21:14:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

             ds         yhat   yhat_lower   yhat_upper
1000 2025-09-27  8858.638047  8706.357779  9009.011965
1001 2025-09-28  8846.119933  8694.794382  9022.682181
1002 2025-09-29  8849.596239  8689.399480  9026.881030
1003 2025-09-30  8833.707127  8671.788419  8993.224037
1004 2025-10-01  8815.977470  8664.423441  8984.118113
1005 2025-10-02  8815.012624  8652.978803  8986.817545
1006 2025-10-03  8794.814684  8637.076875  8969.184632
1007 2025-10-04  8756.843109  8598.234311  8924.378024
1008 2025-10-05  8714.323806  8544.804381  8882.801752
1009 2025-10-06  8669.395740  8508.210310  8832.463524
1010 2025-10-07  8639.822811  8475.577305  8792.297050
1011 2025-10-08  8651.735290  8489.773846  8819.778525
1012 2025-10-09  8667.474523  8510.647491  8831.115499
1013 2025-10-10  8646.095545  8483.443410  8817.176965
1014 2025-10-11  8576.733044  8405.775456  8737.080245
1015 2025-10-12  8495.913760  8337.153698  8663.942105
1016 2025-10-13  8499.538483  8332.959134  8644.273646
1017 2025-10-14  8619.757097  8460.033784  8786.510334
1018 2025-10-15  8855.392708  8681.902998  9028.725605
1019 2025-10-16  9130.524576  8966.019561  9302.650349
1020 2025-10-17  9309.242898  9143.010052  9474.546591
1021 2025-10-18  9355.572936  9198.790893  9512.432413
1022 2025-10-19  9317.690897  9164.001236  9482.268704
1023 2025-10-20  9257.972472  9103.186626  9427.846891
1024 2025-10-21  9226.483993  9059.448865  9398.733687
1025 2025-10-22  9242.622360  9075.885340  9400.146512
1026 2025-10-23  9253.946704  9077.085312  9419.648050
1027 2025-10-24  9226.745167  9069.531534  9401.223935
1028 2025-10-25  9170.954593  8997.568114  9346.586764
1029 2025-10-26  9119.286948  8957.528276  9283.499938